In [1]:
import numpy as np
import time
import math
import scipy
from matplotlib import pyplot as plt
from sompy import SOMFactory
from view_1st import View2DN 
from cartpole_1 import to_cut, readgmc, readgmc1, map_long, findbmu, karma_ca, testgm
mapsize = [50,50]
nvlimit = 20

In [4]:
use_cut = np.array(to_cut(readgmc,epi = 1000))
#to get trainning data, within 1000 epis
sm = SOMFactory().build(use_cut, mapsize= mapsize, lattice = 'mirror', normalization = 'var', initialization='random')
A = sm.train(n_job=1, verbose=False, train_rough_len=2, train_finetune_len=1, nth=1)
print(sm.codebook.mapsize)
#Creat a Self-Organizing Map on those data
po = map_long(readgmc1,sm.codebook.matrix,findbmu, 20, epi = 25000)
print(np.shape(po))
#record winning expeiences, including observing and actions
K = karma_ca(po, 2500)
#decide what to act for every SOM neuron


[50, 50]
agent array is [[ 819   23   -1]
 [2480   23   -1]
 [1495   22   -1]
 ...
 [1597   32   -1]
 [1598   32   -1]
 [2431   32    1]]
(119912, 3)


In [6]:
testgm(sm.codebook.matrix,K,epi = 15)

finished after 121 steps
finished after 500 steps
finished after 369 steps
finished after 500 steps
finished after 500 steps
finished after 500 steps
finished after 462 steps
finished after 143 steps
finished after 139 steps
finished after 500 steps
finished after 500 steps
finished after 500 steps
finished after 386 steps
finished after 424 steps
finished after 500 steps
